export const ADD_SPORTSCHOOL = "ADD_SPORTSCHOOL";
export const LOAD_SPORTSCHOOLS = "LOAD_SPORTSCHOOLS";
export const GET_SPORTSCHOOL = "GET_SPORTSCHOOL";
export const DOWNLOAD_SPORTSCHOOLS = "DOWNLOAD_SPORTSCHOOLS";

export const ADD_ATHLETE = "ADD_ATHLETE";
export const LOAD_ATHLETES = "LOAD_ATHLETES";
export const GET_ATHLETE = "GET_ATHLETE";
export const GET_ATHLETES_FEE = "GET_ATHLETES_FEE";
export const DOWNLOAD_ATHLETES = "DOWNLOAD_ATHLETES";


export const SPECIALIZATION_GROUPS = "SPECIALIZATION_GROUPS";
export const NO_SPECIALIZATION_GROUPS = "NO_SPECIALIZATION_GROUPS";
export const GROUP_SCHEDULES = "GROUP_SCHEDULES";